const data = [
  {
    id: 1,
    name: "Neset kaymak",
    spouseIds: [2],
    children: [3, 4],
    lived: "1111-1111",
  },
  {
    id: 2,
    name: "Yurdagul kaymak",
    spouseIds: [1, 7],
    children: [3, 4],
    lived: "1111-1111",
  },
  // {
  //   id: 3,
  //   name: "Kemal kaymak",
  //   spouseIds: [5],
  //   children: [],
  //   lived: "1111-1111",
  // },
  // {
  //   id: 4,
  //   name: "Omer kaymak",
  //   spouseIds: [6],
  //   children: [],
  //   lived: "1111-1111",
  // },
  // {
  //   id: 5,
  //   name: "Haci Hanim kaymak",
  //   spouseIds: [3],
  //   children: [],
  //   lived: "1111-1111",
  // },
  // {
  //   id: 6,
  //   name: "Rahime kaymak",
  //   spouseIds: [4],
  //   children: [],
  //   lived: "1111-1111",
  // },
  {
    id: 7,
    name: "yeni kaymak",
    spouseIds: [2],
    children: [],
    lived: "1111-1111",
  },
];
