var nodes = [];
var links = [];
var linkUps = [];
var canvas;
var designMode = true;
var selectedElementForUpdate = null;
var canvasDragging = false;
const designBtn = document.getElementById("mode-btn");
const nameInp = document.getElementById("name-inp");
const dateInp = document.getElementById("date-inp");
const menuItemsContainer = document.querySelector(".menu-items-container");
const popupContainer = document.querySelector(".popup-container");
