var nodes = [];
var links = [];
var linkUps = [];
var canvas;
var designMode = true;
var selectedElementForUpdate = null;
var canvasDragging = false;
var fileController;
var selectMode = false;
var select;
var selected = [];
var zoomLevel = 1;
var panX = 0;
var panY = 0;
var panDragStartMouseX = 0;
var panDragStartMouseY = 0;
var panDragStartPanX = 0;
var panDragStartPanY = 0;

var isTouching = false;
var touchPanActive = false;
var touchDragActive = false;
var touchedNodeRef = null;
var lastTapTime = 0;
var lastTapNode = null;
var longPressTimer = null;
var longPressTriggered = false;
var pinchStartDist = 0;
var pinchStartZoom = 1;
var touchStartX = 0;
var touchStartY = 0;

const designBtn = document.getElementById("mode-btn");
const nameInp = document.getElementById("name-inp");
const dateInp = document.getElementById("date-inp");
const boxColorInp = document.getElementById("box-clr");
const textColorInp = document.getElementById("text-clr");
const strokeColorInp = document.getElementById("stroke-clr");
const popupContainer = document.querySelector(".popup-container");
